---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 'Dopo che l"hardware AFX è stato installato, puoi completare la configurazione del cluster ONTAP. Questo processo prevede fasi di configurazione correlate che dovresti eseguire in sequenza. Come parte di questo, puoi opzionalmente aggiungere i nodi di calcolo dati (DCN) che eseguono l"AI Data Engine (AIDE), consentendo al cluster storage AFX e al cluster DCN di operare come un unico sistema gestito tramite lo stesso piano di controllo ONTAP.' 
---
= Configura il tuo cluster ONTAP del sistema di archiviazione AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo che l'hardware AFX è stato installato, puoi completare la configurazione del cluster ONTAP. Questo processo prevede fasi di configurazione correlate che dovresti eseguire in sequenza. Come parte di questo, puoi opzionalmente aggiungere i nodi di calcolo dati (DCN) che eseguono l'AI Data Engine (AIDE), consentendo al cluster storage AFX e al cluster DCN di operare come un unico sistema gestito tramite lo stesso piano di controllo ONTAP.



== Preparati a configurare un sistema storage AFX

Prima di configurare il tuo ONTAP cluster, dovresti rivedere i requisiti principali di AFX e le ulteriori considerazioni su AIDE per assicurarti di avere tutte le informazioni e le risorse necessarie per completare con successo il processo di configurazione.



=== Requisiti core AFX

Ci sono diversi requisiti fondamentali da considerare quando si configura il cluster AFX.

.Installazione hardware
Assicurati di aver completato l'installazione hardware del tuo sistema AFX. Per ulteriori informazioni, consulta link:../install-setup/install-setup-workflow.html["Installa il tuo sistema AFX"].

.Indirizzamento IP di base
È necessaria la seguente configurazione di indirizzamento IP:

* Indirizzo IP di gestione del cluster
+
L'indirizzo IP di gestione del cluster è un indirizzo IPv4 univoco per l'interfaccia di gestione del cluster utilizzata dall'amministratore del cluster per accedere all'SVM di amministrazione e gestire il cluster.  Puoi ottenere questo indirizzo IP dall'amministratore responsabile dell'assegnazione degli indirizzi IP nella tua organizzazione.

* Maschera di sottorete di rete
+
Durante la configurazione del cluster, ONTAP richiede un set di interfacce di rete appropriate per la configurazione.  Se necessario, è possibile modificare la raccomandazione.



.Configurazione di rete aggiuntiva
Avrai inoltre bisogno delle seguenti informazioni di rete correlate:

* Indirizzo IP del gateway di rete
* nomi di dominio DNS
* Indirizzi IP del server dei nomi DNS
* Indirizzi IP del server NTP
* Maschera di sottorete




=== Ulteriori considerazioni AIDE

Quando installi e configuri AFX per la prima volta, puoi facoltativamente includere NetApp AI Data Engine (AIDE). Se intendi configurare AIDE, dovrai prima fare quanto segue:

* Assicurarsi di  https://docs.netapp.com/us-en/ai-data-engine/install-setup/aide-hardware-requirements.html["installare AIDE"^] e collegare i nodi di elaborazione alla rete storage AFX.
* Ottieni gli indirizzi e qualsiasi configurazione di rete correlata per i nodi di elaborazione dati.




== Eseguire la configurazione iniziale del cluster

È possibile collegare il dispositivo portatile al cluster AFX e impostare diversi valori di configurazione globali.

.Informazioni su questo compito
Ci sono quattro aree del cluster AFX che devono essere inizialmente configurate.  I primi tre sono obbligatori, mentre l'ultimo è facoltativo.

.Passi
. Scopri la tua rete di cluster.
+
.. Collega il tuo laptop allo switch di gestione e accedi ai computer e ai dispositivi della rete.
.. Aprire Esplora file.
.. Selezionare *Rete*, quindi fare clic con il pulsante destro del mouse e selezionare *Aggiorna*.
.. Selezionare l'icona ONTAP , quindi accettare tutti i certificati visualizzati sullo schermo.
+
Viene visualizzata l'interfaccia utente di System Manager.



. Imposta la password dell'amministratore.
+
Fornire e verificare la password per il `admin` account. Selezionare *Continua*.

. Configura gli indirizzi IP per il cluster AFX e i nodi controller.
+
Fornire gli indirizzi IP e le maschere di sottorete.

. Se si installa AI Data Engine con il sistema storage AFX, fornire gli indirizzi IP per i tre nodi AIDE DCN.
. Configura i servizi di rete, inclusi DNS e NIS. Seleziona *Continue*.
+
Definisci i dettagli per i tuoi server DNS e NTP.

. Facoltativamente, impostare la crittografia.
+
È possibile definire i dettagli per la crittografia del cluster. Selezionare *Continua*.

+

NOTE: Per informazioni su come creare un cluster per un ambiente non Windows, vedere link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["Crea un cluster ONTAP e unisci i nodi"^].



.Cosa c'è dopo?
Verrai reindirizzato alla pagina di accesso di System Manager.  Eseguire i passaggi descritti in<<Configurazione completa del cluster>> .



== Configurazione completa del cluster

Dopo aver eseguito la configurazione iniziale, è possibile completare l'installazione del cluster ONTAP utilizzando System Manager.

.Informazioni su questo compito
Durante la configurazione vengono configurate tre aree del cluster ONTAP del sistema AFX.  Se possibile, completa tutti e tre i punti, ma è obbligatorio solo il primo.

.Prima di iniziare
È necessario disporre delle seguenti informazioni:

* Dettagli sulla configurazione VLAN.
* Dettagli sulla configurazione NAS e/o S3.


.Passi
. Sign in a System Manager utilizzando l'account amministratore fornito durante la configurazione iniziale del cluster.  Notare la finestra popup in alto a destra con tre opzioni di configurazione.
. Selezionare *VLAN e tagging* e selezionare le opzioni di rete appropriate per il proprio ambiente.
. Selezionare *Servizi di rete* e configurare i protocolli di accesso client per l'SVM dati predefinito.
. Seleziona *Contenitore dati* e crea un volume o un bucket S3.


.Cosa c'è dopo?
* Se hai incluso AIDE come parte della configurazione del cluster AFX, dovrai eseguire ulteriori passaggi di configurazione, tra cui la licenza e l'autenticazione. Consulta  https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["Imposta AI Data Engine"^] per ulteriori informazioni.
* Dovrestilink:../get-started/prepare-cluster-admin.html["Prepararsi a somministrare AFX"] prima di utilizzare il cluster AFX in un ambiente di produzione.




== Informazioni correlate

* link:../get-started/learn-about-aide.html["Scopri il NetApp AI Data Engine"]
* link:../administer/configure-svm.html["Configurare un AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["Prepararsi a somministrare AFX"]

