---
sidebar: sidebar 
permalink: faq-ontap-afx.html 
keywords: afx, afx system, faq, frequently asked questions 
summary: Questo elenco di FAQ fornisce le risposte alle domande che i clienti solitamente hanno sul loro sistema di archiviazione AFX.  Include concetti e terminologia che possono essere utili quando si esplora AFX in modo più dettagliato o si eseguono attività amministrative avanzate. 
---
= FAQ sui sistemi di archiviazione AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa lista di FAQ fornisce le risposte alle domande che potresti avere sul tuo sistema di archiviazione AFX.  Include concetti e terminologia che possono essere utili quando si esplora AFX in modo più dettagliato o si eseguono attività amministrative avanzate.



== Generale

.Cos'è una personalità ONTAP ?
ONTAP è una piattaforma di storage robusta e versatile, nota per il suo set completo di funzionalità e la sua adattabilità a un'ampia gamma di requisiti di storage.  Sebbene questa flessibilità lo renda una scelta eccellente per le organizzazioni con carichi di lavoro diversificati, alcuni clienti possono trarre vantaggio da una soluzione di archiviazione più personalizzata, ottimizzata per le esigenze del loro ambiente specifico.

Per soddisfare queste esigenze specifiche, alcuni sistemi di storage NetApp offrono distinte personalità ONTAP , ciascuna delle quali include un set di funzionalità progettato per supportare i requisiti specifici del cliente.  Una personalità ONTAP è in genere una combinazione di funzionalità hardware e software ed è progettata appositamente per offrire un'esperienza ottimizzata per casi d'uso mirati.  NetApp fornisce tre personalità ONTAP :

* *Unified ONTAP* - La personalità Unified ONTAP offre un'ampia gamma di funzionalità di gestione dei dati, supportando i protocolli NAS, SAN e S3 per la massima flessibilità. Si tratta dell'offerta di punta NetApp , disponibile sui sistemi AFF e FAS , nonché su distribuzioni virtualizzate come ONTAP Select e Cloud Volumes ONTAP.
* *AFX* - La personalità AFX ONTAP fornisce una soluzione disaggregata progettata per soddisfare i rigorosi requisiti dei carichi di lavoro NAS e S3 ad alte prestazioni, comprese le applicazioni AI/ML. I sistemi AFX offrono funzionalità specializzate per i clienti che necessitano di un'archiviazione di file e oggetti scalabile e ad alta produttività.
* * ASA r2* - La personalità ASA r2 ONTAP fornisce una soluzione disaggregata progettata specificamente per ambienti SAN-only. https://docs.netapp.com/us-en/asa-r2/["Sistemi ASA r2"^]  semplificare l'esperienza di archiviazione per i carichi di lavoro a blocchi, offrendo una gestione semplificata e prestazioni ottimizzate per i clienti SAN.


Offrendo queste distinte personalità ONTAP , NetApp consente alle organizzazioni di selezionare una soluzione di storage in linea con i loro requisiti operativi e carichi di lavoro applicativi.

.Posso modificare la personalità ONTAP del mio sistema di storage NetApp ?
No. La personalità del tuo sistema di archiviazione ONTAP è immutabile e non può essere modificata.  Ad esempio, non è possibile convertire o aggiornare un sistema di archiviazione FAS o AFF (che esegue la personalità Unified ONTAP ) in un sistema di archiviazione AFX.

.Le interfacce di System Manager per le diverse personalità ONTAP sono tutte molto simili.  Come posso determinare la personalità di un sistema specifico?
In System Manager, seleziona *Cluster* nel riquadro di navigazione a sinistra, quindi *Panoramica*.  Vedrai la personalità visualizzata sulla pagina.  In alternativa, è possibile impartire il comando "system node show" dalla CLI.  È anche possibile determinare la personalità di un cluster ONTAP utilizzando l'API REST; vederelink:./rest/first-call.html["La tua prima chiamata API REST del sistema AFX"] per i dettagli.

.Quando sono diventati disponibili i sistemi di stoccaggio AFX? Qual è la prima versione ONTAP supportata da AFX?
Il sistema di storage AFX è stato annunciato alla conferenza NetApp Insight nell'ottobre 2025. AFX supporta ONTAP 9.17.1 e versioni successive. Per maggiori dettagli, contatta il tuo rappresentante commerciale NetApp .

.Cosa significa "disaggregato" nel contesto dei sistemi di archiviazione AFX?
Il termine "disaggregato" può avere due significati diversi, seppur correlati, con AFX a seconda del contesto.

Un concetto importante da cui partire è il disaccoppiamento della capacità di elaborazione nei nodi controller dagli scaffali di archiviazione.  Con AFX, i componenti di elaborazione e archiviazione del cluster non sono più strettamente accoppiati come nei sistemi FAS e AFF , che eseguono la personalità Unified ONTAP .  Invece sono collegati tramite switch cluster.  Ogni controller di nodo AFX ha una vista completa dell'intero pool di archiviazione del cluster.

Il secondo concetto correlato all'archiviazione disaggregata è che gli aggregati e la gestione RAID vengono rimossi come entità amministrabili.  Un livello di astrazione dell'archiviazione all'interno di AFX configura e gestisce automaticamente gli aspetti di basso livello dell'archiviazione, inclusi i dischi fisici e i gruppi RAID.  Ciò consente all'amministratore AFX di concentrarsi sulla configurazione di archiviazione di alto livello basata su volumi e bucket.



== Interoperabilità

.Posso combinare i nodi del sistema AFX con i nodi del sistema AFF, ASA o FAS nello stesso cluster ONTAP ?
No. Non è possibile combinare nodi di sistema che eseguono diverse personalità ONTAP nello stesso cluster. Ad esempio, non è possibile combinare nodi AFX (che eseguono la personalità AFX ONTAP ) con nodi AFF o FAS (che eseguono la personalità Unified ONTAP ) nello stesso cluster.

.Posso utilizzare FlexCache con un cluster di sistema AFX?
Sì. I sistemi di archiviazione AFX supportano FlexCache sia da che verso un sistema AFF o FAS che esegue la personalità Unified ONTAP . L'unica limitazione è che FlexCache con modalità write-back non è supportato con AFX.

.Se voglio utilizzare un sistema AFF o FAS (che esegue la personalità Unified ONTAP ) con un sistema AFX per SnapMirror o FlexCache, quale versione ONTAP mi serve?
Le regole della versione SnapMirror per AFX sono identiche a quelle di Unified ONTAP.  Ciò significa che per replicare da Unified ONTAP, il sistema di origine deve essere compreso nell'intervallo di versioni supportato.  Per replicare da AFX, il sistema Unified ONTAP deve essere ONTAP 9.16.1 o versione successiva (la prima versione supportata dalla funzionalità Advanced Capacity Balancing).  Per FlexCache, le stesse regole si applicano ai sistemi di origine e di destinazione come descritto in https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743"^] .

Esistono alcune differenze nel supporto per i volumi FlexGroup .  Un volume FlexGroup su AFX non può essere un volume di origine per un volume FlexCache che utilizza la modalità Writeback.

.Posso effettuare chiamate API ONTAPI (ZAPI) a un cluster AFX?
No. AFX supporta solo l'API REST ONTAP .  Qualsiasi codice di automazione che utilizza ZAPI deve essere convertito in REST API per essere utilizzato con AFX.



== Concetti avanzati

.Quali sono i protocolli dati supportati da un sistema di archiviazione AFX?
I protocolli dati supportati da AFX includono quanto segue:

* NFSv3, NFSv4.0, NFSv4.1, NFSv4.2
* SMB2.x, SMB3.x
* S3
* NDMP


.I protocolli dati funzionano in modo diverso in AFX?
No. I protocolli dati in AFX funzionano allo stesso modo dei sistemi AFF e FAS .

.In AFX viene utilizzato il partizionamento avanzato del disco (ADP)?
No. ADP non viene utilizzato con AFX.  Poiché con AFX non sono presenti aggregati radice, la funzionalità ADP non è necessaria per massimizzare l'efficienza dello spazio su disco.

.Posso utilizzare qualsiasi tipo di switch nella rete del cluster backend per il mio sistema di archiviazione AFX?
No. Per la rete cluster sono supportati solo gli switch specificamente approvati e forniti con la piattaforma di storage AFX. Inoltre, questi switch backend sono dedicati alle operazioni del cluster AFX. Le operazioni di accesso client (tramite NFS, SMB e S3) devono essere eseguite solo sulla rete dati client frontend.

.Come sono configurati gli switch del cluster?
Gli switch di rete del cluster vengono configurati tramite un file di configurazione fornito da NetApp. Le modifiche al file di configurazione non sono supportate.

.Come è organizzato lo storage in un cluster AFX?
Tutti i dischi e gli scaffali di archiviazione collegati a un cluster AFX fanno parte di una Storage Availability Zone (SAZ).  Ogni cluster AFX supporta una sola SAZ che non può essere condivisa tra i cluster AFX (ad eccezione delle operazioni di replica SnapMirror e FlexCache ).

Ogni nodo ha visibilità su tutto lo storage nella SAZ.  Quando si aggiungono ripiani di archiviazione a un cluster, ONTAP aggiunge automaticamente i dischi.

.In che modo le operazioni di spostamento dei volumi funzionano in modo diverso con i sistemi AFX rispetto ai sistemi AFF o FAS ?
Con i sistemi AFF e FAS , che eseguono la personalità Unified ONTAP , è possibile spostare un volume senza interruzioni da un nodo o aggregarlo a un altro nel cluster. Questa operazione viene eseguita tramite un'operazione di copia in background con tecnologia SnapMirror , in cui viene creato un nuovo volume di destinazione nella nuova posizione. A seconda delle dimensioni del volume e dell'utilizzo delle risorse del cluster, il tempo necessario per completare lo spostamento di un volume può variare.

Con AFX non ci sono aggregati.  Tutto lo storage è contenuto in un'unica Storage Availability Zone, accessibile da ogni nodo del cluster.  Di conseguenza, gli spostamenti di volume non hanno mai bisogno di copiare effettivamente i dati.  Invece, tutti gli spostamenti di volume vengono eseguiti con aggiornamenti dei puntatori tra i nodi.  Questa operazione è denominata Zero Copy Volume Move (ZCVM) e avviene istantaneamente perché in realtà non vengono copiati o spostati dati.  Si tratta essenzialmente dello stesso processo di spostamento del volume utilizzato con Unified ONTAP senza la copia SnapMirror .

Nella versione iniziale di AFX, i volumi verranno spostati solo in scenari di failover dello storage e quando i nodi vengono aggiunti o rimossi dal cluster. Questi spostamenti sono controllati solo tramite ONTAP.

.In che modo AFX determina dove posizionare i dati nella SAZ?
AFX include una funzionalità nota come Automated Topology Management (ATM) che risponde agli squilibri degli oggetti utente e del sistema.  L'obiettivo principale dell'ATM è bilanciare i volumi nel cluster AFX.  Quando viene rilevato uno squilibrio, viene attivato un processo interno per distribuire uniformemente i dati tra i nodi attivi.  I dati vengono riallocati tramite ZCVM, che deve solo copiare e aggiornare i metadati dell'oggetto.
