---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'I sistemi NetApp AFX eseguono una personalità personalizzata di ONTAP che differisce dalla personalità ONTAP (denominata Unified ONTAP) in esecuzione su storage AFF e FAS .  È necessario essere consapevoli delle somiglianze e delle differenze tra i sistemi AFX e FAS e AFF .  Ciò fornisce una prospettiva preziosa e può essere utile quando si distribuisce AFX nel proprio ambiente.' 
---
= Confronta il sistema di archiviazione AFX con i sistemi AFF e FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi NetApp AFX eseguono una personalità personalizzata di ONTAP che differisce dalla personalità ONTAP (denominata Unified ONTAP) in esecuzione su storage AFF e FAS .  È necessario essere consapevoli delle somiglianze e delle differenze tra i sistemi AFX e FAS e AFF .  Ciò fornisce una prospettiva preziosa e può essere utile quando si distribuisce AFX nel proprio ambiente.


TIP: La documentazione AFX include collegamenti a vari argomenti sul sito di documentazione Unified ONTAP per informazioni dettagliate sulle funzionalità che si comportano allo stesso modo indipendentemente dalla personalità ONTAP .  I contenuti aggiuntivi forniscono informazioni più approfondite che possono rivelarsi utili durante la gestione del sistema di archiviazione AFX.



== Differenze di configurazione

Ci sono alcuni aspetti in cui la configurazione AFX differisce dai sistemi AFF e FAS .

Bilanciamento avanzato della capacità:: La funzione avanzata di bilanciamento della capacità, controllata tramite `-gdd` Parametro CLI, abilitato per impostazione predefinita per tutti i volumi FlexGroup .




== Funzionalità Unified ONTAP non supportate o limitate

NetApp AFX è ottimizzato per carichi di lavoro NAS e oggetti ad alte prestazioni.  Per questo motivo, esistono differenze tra AFF e FAS , nonché con gli altri sistemi di archiviazione Unified ONTAP .  Le seguenti funzionalità non sono disponibili con NetApp AFX; l'elenco è organizzato in base alla funzionalità principale o all'area funzionale.  Dovresti anche rivedere gli aggiornamenti e le modifiche per AFX inlink:../release-notes/whats-new-9171.html["Cosa c'è di nuovo"] in base alla tua versione.



=== Blocco e SAN

* Amministrazione SAN e accesso client
* LUN e spazi dei nomi NVMe
* Provisioning denso dei volumi




=== Aggregati e archiviazione fisica

* MetroCluster
* Aggregati di proprietà dei nodi fisici
* Gestione RAID
* Crittografia aggregata NetApp (NAE)
* Deduplicazione a livello di aggregato
* SyncMirror (mirroring aggregato)
* Struttura a FabricPool




=== Replica dei dati (SnapMirror)


NOTE: Tutta la replica dei dati è supportata in entrambe le direzioni tra Unified ONTAP e AFX con le stesse restrizioni di versione descritte in https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Versioni ONTAP compatibili per le relazioni SnapMirror"^] (con alcune piccole eccezioni).

* Nessuna replica di un volume da un sistema AFF o FAS che contiene uno spazio dei nomi LUN o NVMe
* I volumi FlexGroup possono essere replicati solo da AFX a Unified ONTAP versione 9.16.1 o successiva (a causa della necessità di Advanced Capacity Balancing)




=== Gestibilità

* API ONTAPI (ZAPI)
* API REST per funzionalità non supportate (come MetroCluster)
* Alcune limitazioni iniziali sulle API REST per le statistiche sulle prestazioni
* Supporto AIQ Unified Manager
* Grafana Harvest versione 25.08.1 e successive
* NetApp Trident versione 25.10 e successive




== Modifiche all'interfaccia della riga di comando

La CLI ONTAP disponibile con AFX rispecchia generalmente la CLI disponibile con i sistemi AFF e FAS .  Ma ci sono diverse differenze, tra cui:

* Nuovi comandi AFX relativi a:
+
** Visualizzazione della capacità della zona di disponibilità dello storage
** Supporto di avvio


* Nessun comando correlato a SAN
* I comandi di gestione degli aggregati non sono più necessari
* La visualizzazione aggregata ora mostra l'intera Storage Availability Zone (SAZ)




== Informazioni correlate

* link:../get-started/system-design.html["Caratteristiche del sistema AFX"]
* link:../get-started/software-architecture.html["Dettagli dell'architettura AFX"]
* link:../faq-ontap-afx.html["FAQ sui sistemi di archiviazione AFX"]
* link:../administer/additional-ontap-cluster.html["Amministrazione aggiuntiva del cluster AFX"]
* link:../administer/additional-ontap-svm.html["Amministrazione aggiuntiva AFX SVM"]

