---
sidebar: sidebar 
permalink: release-notes/changes-to-limits-defaults.html 
keywords: release notes, changes, updates, defaults, limits, afx storage system, afx system, afx 
summary: Scopri le modifiche ai limiti e alle impostazioni predefinite che interessano i sistemi AFX. NetApp si impegna ad aiutare i propri clienti a comprendere le modifiche più importanti alle impostazioni predefinite e ai limiti in ogni release di ONTAP. 
---
= Modifiche ai limiti e alle impostazioni predefinite di ONTAP che interessano i sistemi AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri le modifiche ai limiti e alle impostazioni predefinite che interessano i sistemi AFX. NetApp si impegna ad aiutare i propri clienti a comprendere le modifiche più importanti alle impostazioni predefinite e ai limiti in ogni release di ONTAP.


TIP: Per determinare le capacità del tuo cluster AFX, dovresti consultare i dettagli disponibili su NetApp Hardware Universe e Interoperability Matrix Tool.



[[changes-to-ontap-limits]]
== Modifiche ai limiti ONTAP

[cols="1,3,1"]
|===
| Caratteristica | Modifica limite | Modificato nella versione 


| Nodi per cluster  a| 
Puoi espandere il tuo cluster AFX fino a un massimo di 32 nodi. Questo ti permette di scalare il tuo sistema storage AFX per soddisfare le crescenti esigenze dei tuoi carichi di lavoro e delle tue applicazioni. Nota che il supporto per 32 nodi è disponibile con un set di funzionalità limitato; consulta il tuo team account NetApp per i dettagli.
| ONTAP 9.19.1 


| Volumi per FlexGroup  a| 
Il numero massimo di volumi in un FlexGroup è stato aumentato a 512 con 32 nodi. Questo permette al sistema storage AFX di offrire appieno le capacità prestazionali per cluster di grandi dimensioni.
| ONTAP 9.19.1 
|===


[[related-information]]
== Informazioni correlate

* https://hwu.netapp.com/["Hardware Universe NetApp"^]
* https://imt.netapp.com/["Strumento matrice di interoperabilità NetApp"^]
* https://docs.netapp.com/us-en/interoperability-matrix-tool/["Panoramica dello strumento matrice di interoperabilità"^]

