---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Scopri le nuove funzionalità incluse in ONTAP 9.18.1 disponibili con il tuo sistema di archiviazione AFX. 
---
= Novità di ONTAP 9.18.1 per i sistemi di storage AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità incluse in ONTAP 9.18.1 disponibili con il tuo sistema di archiviazione AFX.



== Miglioramenti nella gestione delle risorse di archiviazione

[cols="2,4"]
|===
| Aggiornamento | Descrizione 


| Posizionamento del volume migliorato  a| 
NetApp AFX bilancia automaticamente il posizionamento dei volumi su tutti i nodi di un cluster.  Nelle precedenti versioni ONTAP , l'algoritmo di posizionamento si basava sul numero di volumi nel cluster.  A ogni nodo viene assegnato lo stesso numero di volumi, indipendentemente dall'attività.  A partire da ONTAP 9.18.1, l'algoritmo è stato migliorato per considerare le prestazioni dei nodi durante il posizionamento o lo spostamento dei volumi.  Ciò si traduce in un migliore bilanciamento delle prestazioni tra i nodi del cluster AFX e riduce notevolmente la probabilità che un singolo nodo si sovraccarichi.

|===
.Informazioni correlate
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Punti salienti della versione ONTAP 9"^]

