---
sidebar: sidebar 
permalink: release-notes/whats-new-9191.html 
keywords: 'afx, release notes, what"s new, 9.19.1, ai data engine, aide' 
summary: Scopri le nuove funzionalità incluse in ONTAP 9.19.1 che sono disponibili con il tuo sistema storage AFX. 
---
= Novità di ONTAP 9.19.1 per i sistemi di storage AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità incluse in ONTAP 9.19.1 che sono disponibili con il tuo sistema storage AFX.


TIP: Scopri il nuovo e migliorato supporto per  https://docs.netapp.com/us-en/ai-data-engine/release-notes/whats-new.html["AI Data Engine"^].



== Prestazioni e scala

[cols="2,4"]
|===
| Aggiornamento | Descrizione 


| Dimensione del cluster AFX espansa  a| 
ONTAP 9.19.1 supporta l'espansione di un cluster AFX fino a un massimo di 32 nodi. Ciò consente di scalare il sistema storage AFX per soddisfare le crescenti esigenze dei carichi di lavoro e delle applicazioni.



| Lettura sequenziale tra file (CFSR)  a| 
La funzione Cross File Sequential Read può migliorare significativamente le prestazioni di lettura per determinati carichi di lavoro multimediali e di intrattenimento. La funzione precarica in modo intelligente i fotogrammi video sequenziali per migliorare drasticamente il throughput e ridurre la latenza per le applicazioni di editing video. Consulta link:../administer/additional-ontap-svm.html["Amministrazione aggiuntiva per un sistema di archiviazione AFX SVM"] per ulteriori informazioni.



| Deduplicazione globale  a| 
La deduplicazione globale estende il risparmio di spazio derivante dalla deduplicazione ONTAP all'intera Storage Availability Zone (SAZ). Eliminando i blocchi di dati duplicati in tutti i volumi della SAZ, è possibile migliorare significativamente l'efficienza dello storage e ridurre il costo totale di proprietà. Questa funzionalità è abilitata di default sui sistemi AFX e opera in modo trasparente senza necessità di configurazione amministrativa. Consultare link:../administer/additional-ontap-svm.html["Amministrazione aggiuntiva per un sistema di archiviazione AFX SVM"] per ulteriori informazioni.

|===


== API REST

[cols="2,4"]
|===
| Aggiornamento | Descrizione 


| Ottimizzazione del posizionamento bilanciato per l'orchestrazione dello storage di Kubernetes  a| 
ONTAP 9.19.1 aggiunge sei parametri attualmente disponibili nell'endpoint  `/storage/volumes` REST API all'endpoint  `/applications/containers`. Questo miglioramento consente ai clienti che utilizzano NetApp Trident per l'orchestrazione dello storage Kubernetes di creare volumi con la funzionalità nativa di posizionamento bilanciato di ONTAP.

|===


== Sicurezza

[cols="2,4"]
|===
| Aggiornamento | Descrizione 


| Supporto ARP/AI per volumi primari idonei SnapMirror  a| 
ARP/AI supporta volumi primari idonei in relazioni SnapMirror sincrone con i sistemi AFX. ARP/AI viene eseguito sul volume primario attivo in lettura/scrittura, crea snapshot ARP solo per il volume primario e fornisce il rilevamento di ransomware basato sull'apprendimento automatico.



| link:../administer/additional-ontap-cluster.html["Supporto per l'offload hardware TLS"]  a| 
È possibile delegare la crittografia e la decrittografia Transport Layer Security (TLS) dell'intero cluster alle schede Ethernet supportate. Ciò riduce il carico sulla CPU e migliora le prestazioni dei sistemi che utilizzano TLS.

|===


== gestione delle risorse di storage

[cols="2,4"]
|===
| Aggiornamento | Descrizione 


| link:../administer/monitor-cluster-performance.html["Supporto di System Manager per i dettagli sulla capacità delle zone di disponibilità dello storage."]  a| 
È possibile visualizzare i dettagli della capacità della zona di disponibilità dello storage, inclusi le soglie di spazio, lo spazio consumato dalle snapshot e la riduzione dei dati in System Manager. È inoltre possibile impostare le soglie di utilizzo dello spazio in base alla percentuale oltre la quale si desidera che ONTAP generi avvisi e notifiche critiche.



| link:../administer/additional-ontap-cluster.html["Supporto per la modifica delle impostazioni predefinite che controllano gli aumenti automatici del limite massimo di throughput QoS"]  a| 
È possibile modificare le impostazioni predefinite che controllano il modo in cui i gruppi di criteri QoS aumentano automaticamente il limite massimo di throughput QoS in risposta a esigenze a breve termine di prestazioni superiori. Queste impostazioni non possono essere modificate in ONTAP 9.18.1 e versioni precedenti.

|===


== Aggiornamento

[cols="2,4"]
|===
| Aggiornamento | Descrizione 


| link:../administer/upgrade-ontap.html["Funzionalità di reporting migliorate per i controlli automatici pre-aggiornamento"]  a| 
Durante l'esecuzione dei controlli automatici pre-aggiornamento, gli errori e gli avvisi vengono visualizzati separatamente per consentire di identificare facilmente i problemi che devono essere risolti prima di procedere con l'aggiornamento.

|===
.Informazioni correlate
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Punti salienti della versione ONTAP 9"^]

